config/routes.rb
Rails.application.routes.draw do
  resources :products
end

app/models/available_product.rb
class AvailableProduct < ActiveRecord::Base
  belongs_to :product
  belongs_to :color
  belongs_to :size
  
  validates :color, :size, :quantity,  presence: true  
end

app/models/color.rb
class Color < ActiveRecord::Base
  has_many :available_products

  validates :name, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :available_products, dependent: :destroy 
  accepts_nested_attributes_for :available_products, reject_if: :all_blank, allow_destroy: true

  validates :name, presence: true

  def build_product_relations
    available_products.build if available_products.blank?
  end   
end

app/models/size.rb
class Size < ActiveRecord::Base
  has_many :available_products

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
    @product.build_product_relations
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to products_path, notice: 'Produto Cadastrado.'
    else
      flash.now[:error] = "Could not save client"
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id]) 
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      if params[:remove_available_products].present?
        params[:remove_available_products].each do |id|
          @product.available_products.destroy(AvailableProduct.find id.to_i)
        end
      end

      redirect_to products_path, notice: 'Produto Atualizado.'
    else
      render :new
    end
  end

  def destroy
    Product.find(params[:id]).destroy

    redirect_to products_path, notice: 'Produto Removido.'
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, available_products_attributes: [:id, :color_id, :size_id, :quantity, :_destroy])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light nav-margin">
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to "Lista de Produtos", products_path, id: "products", class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Cadastrar Produto", new_product_path, id: "new-product", class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Teste Synergia Rails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'header' %>
  <div class="container-fluid div-body">
    <div class="row">
      <%= yield %>
    </div>
  </div>  
</body>
</html>

app/views/products/_available_product_fields.html.erb
<div class="nested-fields row">
  <div class="field col-lg-4">
    <%= f.label :color_id %>
    <%= f.collection_select :color_id, Color.all, :id, :name, {prompt:"Selecione uma Cor"}, { class: 'custom-select' } %>
  </div>
  <div class="field col-lg-4">
    <%= f.label :size_id %>
    <%= f.collection_select :size_id, Size.all, :id, :name, {prompt:"Selecione um Tamanho"}, { class: 'custom-select' } %>
  </div>
  <div class="field col-lg-3">
    <%= f.label :quantity %>
    <%= f.text_field :quantity, placeholder: 'Quantidade', class: 'form-control' %>
  </div>
  <div class="links col-lg-1 margin-btn">
    <%= link_to_remove_association "Excluir", f , class:"btn btn-light" %> 
  </div>
</div>
 

app/views/products/_form.html.erb
<% if @product.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </div>
<% end %>
<%= form_for @product do |f| %>
  <div class="row">
    <div class="field col-sm-6">
      <%= f.label :name %>
      <%= f.text_field :name, placeholder: "#{t'.name'}", class: 'form-control' %>
    </div>
    <div class="field col-sm-6">
      <%= f.label :description, 'Descrição' %>
      <%= f.text_field :description, placeholder: 'Descrição', class: 'form-control' %>
    </div>
    <div class="field col-sm-12">
      <%= f.fields_for :available_products do |available_product| %>
        <%= render 'available_product_fields', :f => available_product %>
      <% end %>
      <div class="links margin-btn">
        <%= link_to_add_association 'Adicionar Cor', f, :available_products, class:"btn btn-secondary" %>
      </div>
    </div>  
    <div class="col-sm margin-btn ">
      <%= f.submit class:"btn btn-primary btn-lg btn-block" %>
    </div>
  </div>
<% end %>

app/views/products/_product.html.erb
<tr>
  <th><%= product.id%></th>
  <td><%= product.name%></td>
  <td><%= product.description%></td>
  <td>
    <% product.available_products.each do |available_product| %>
      <p>
        <%= available_product.color.name %> - 
        <%= available_product.size.name %> - 
        <%= available_product.size.name %>
      </p>  
    <%end%>  
  </td>
  <td>
    <%= link_to t('.edit'), edit_product_path(product) %>
    <%= link_to t('.destroy'),  product,  method: :delete, data: { confirm: t('.dialogs.destroy') } %>
  </td>
</tr>

app/views/products/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h2><%= t'.product_edit'%></h2>
      <hr/>
      <%= render partial: "form", locals: {product: @product} %>  
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="container">
  <div class="row">
    <h2><%= t'.title'%></h2>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col"><%= t('.name')%></th>
          <th scope="col"><%= t('.description')%></th>
          <th scope="col"><%= t('.color_and_size')%></th>
          <th scope="col"><%= t('.action')%></th>
        </tr>
      </thead>
      <tbody>
        <% @products.each do |product|%>
          <%= render partial: 'product', locals: {product: product} %>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="row">
    <%= link_to t('.product_new'), new_product_path, class: "btn btn-primary" %>
  </div>  
</div>    

app/views/products/new.html.erb
<div class="container">
    <div class="col-lg-12">
      <h2><%= t'.product_new'%></h2>
      <hr/>
      <%= render 'form' %>  
    </div>
  </div>
</div>